continuation_prompt = 'â–¶â–¶ '

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[git_commit]
tag_symbol = " ðŸ· "

[time]
format = "îŽ‹ [$time]($style) "
time_format = "%T %b %d, %Y - %A"
disabled = false
utc_time_offset = "-8"
style = "underline yellow"

[gcloud]
disabled = true

[kubernetes]
disabled = false

[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
renamed = "r"
modified = 'ðŸ“'
staged = '[++\($count\)](green)'
deleted = "âœ˜"
up_to_date = "ï€Œ"

[aws]
symbol = "ïƒ‚  "

[bun]
symbol = "bun "

[c]
symbol = "C "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[daml]
symbol = "daml "

[dart]
symbol = "ðŸŽ¯ "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[directory]
read_only = " ðŸ”’"

[docker_context]
symbol = "ðŸ³ "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[git_branch]
symbol = "î‚  "

[golang]
symbol = "ðŸ¹ "

[guix_shell]
symbol = "guix "

[hg_branch]
symbol = "hg "

[java]
symbol = "â˜• "

[julia]
symbol = "jl "

[helm]
symbol = "âŽˆ "

[hostname]
ssh_symbol = "ðŸŒ"

[kotlin]
symbol = "kt "

[lua]
symbol = "ðŸŒ™ "

[nodejs]
symbol = "îœ˜  "

[memory_usage]
symbol = "ðŸ "

[meson]
symbol = "â¬¢ "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[opa]
symbol = "opa "

[os.symbols]
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "ðŸŽ©  "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Linux = "lnx "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "

[package]
symbol = "ðŸ“¦ "

[perl]
symbol = "ðŸª "

[php]
symbol = "ðŸ˜ "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "ðŸ "

[raku]
symbol = "raku "

[ruby]
symbol = "ðŸ’Ž "

[rust]
symbol = "ðŸ¦€ "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[sudo]
symbol = "ðŸ§™ "

[swift]
symbol = "ðŸ¦ "

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "
