right_format = """
$time
"""

continuation_prompt = 'â–¶â–¶ '

[character]
success_symbol = "[ï‚¤ ](bold green)"
error_symbol = "[î´¾ ](bold red)"
vimcmd_symbol = "[î˜« ](bold green)"
vimcmd_replace_one_symbol = "[î˜« ](bold purple)"
vimcmd_replace_symbol = "[î˜« ](bold purple)"
vimcmd_visual_symbol = "[î˜« ](bold yellow)"

[git_commit]
tag_symbol = " ğŸ· "

[git_metrics]
disabled = false

[time]
format = "[ó±‘† $time]($style) "
time_format = "[%T %b %d, %Y on %A]"
disabled = false
utc_time_offset = "-8"
style = "yellow"

[gcloud]
disabled = true

[kubernetes]
disabled = true
symbol = "ó±ƒ¾ "

[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
renamed = "r"
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
deleted = "âœ˜"
up_to_date = "ï€Œ"

[aws]
symbol = "ïƒ‚  "

[bun]
symbol = "ğŸ¥Ÿ "

[c]
symbol = "î˜ "

[cpp]
symbol = "î˜ "

[cobol]
symbol = "cobol "

[conda]
symbol = "ğŸ…’ "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[daml]
symbol = "'Î› "

[dart]
symbol = "ğŸ¯ "

[deno]
symbol = "ğŸ¦• "

[dotnet]
symbol = "î™ˆ "

[directory]
read_only = " ğŸ”’"
home_symbol = "ó±‚µ "

[docker_context]
symbol = "ğŸ³ "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[git_branch]
symbol = "î‚  "

[golang]
symbol = "ğŸ¹ "

[guix_shell]
symbol = "guix "

[hg_branch]
symbol = "hg "

[java]
symbol = "â˜• "

[julia]
symbol = "jl "

[helm]
symbol = "âˆ "

[hostname]
ssh_symbol = "ğŸŒ"

[kotlin]
symbol = "kt "

[lua]
symbol = "ğŸŒ™ "

[nodejs]
symbol = "îœ˜  "

[memory_usage]
symbol = "ğŸ "

[meson]
symbol = "â¬¢ "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[opa]
symbol = "opa "

[os.symbols]
AIX = "â¿ "
Alpaquita = "ğŸ”” "
AlmaLinux = "ğŸ’  "
Alpine = "ğŸ”ï¸ "
Amazon = "ğŸ™‚ "
Android = "ğŸ¤– "
AOSC = "ğŸ± "
Arch = "ğŸ—ï¸ "
Artix = "ğŸ—ï¸ "
Bluefin = "ğŸŸ "
CachyOS = "ğŸ—ï¸ "
CentOS = "ğŸ’  "
Debian = "ğŸŒ€ "
DragonFly = "ğŸ‰ "
Emscripten = "ğŸ”— "
EndeavourOS = "ğŸš€ "
Fedora = "ğŸ© "
FreeBSD = "ğŸ˜ˆ "
Garuda = "ğŸ¦… "
Gentoo = "ğŸ—œï¸ "
HardenedBSD = "ğŸ›¡ï¸ "
Illumos = "ğŸ¦ "
Kali = "ğŸ‰ "
Linux = "ğŸ§ "
Mabox = "ğŸ“¦ "
Macos = "ğŸ "
Manjaro = "ğŸ¥­ "
Mariner = "ğŸŒŠ "
MidnightBSD = "ğŸŒ˜ "
Mint = "ğŸŒ¿ "
NetBSD = "ğŸš© "
NixOS = "â„ï¸ "
Nobara = "ğŸ© "
OpenBSD = "ğŸ¡ "
OpenCloudOS = "â˜ï¸ "
openEuler = "ğŸ¦‰ "
openSUSE = "ğŸ¦ "
OracleLinux = "ğŸ¦´ "
Pop = "ğŸ­ "
Raspbian = "ğŸ“ "
Redhat = "ğŸ© "
RedHatEnterprise = "ğŸ© "
RockyLinux = "ğŸ’  "
Redox = "ğŸ§ª "
Solus = "â›µ "
SUSE = "ğŸ¦ "
Ubuntu = "ğŸ¯ "
Ultramarine = "ğŸ”· "
Unknown = "â“ "
Uos = "ğŸ² "
Void = "îŠ™ "
Windows = "ğŸªŸ "

[package]
symbol = "ğŸ“¦ "

[perl]
symbol = "ğŸª "

[php]
symbol = "ğŸ˜ "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "ó°Œ  "

[raku]
symbol = "raku "

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "ğŸ¦€ "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[sudo]
symbol = "ğŸ§™ "

[swift]
symbol = "ğŸ¦ "

[terraform]
symbol = "ğŸ’  "

[zig]
symbol = "zig "

[jobs]
symbol = "âœ¦ "
